name: Build and Test
on: pull_request

env:
  working-dir: src

jobs:
  build:
    defaults:
      run:
        working-directory: ${{env.working-dir}}
        
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --configuration Release --no-restore --settings github.runsettings --verbosity normal
