name: Build, Test and Scan
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

env:
  working-dir: src
  test-settings: TeleScope.MSTest/github.runsettings

jobs:
  build:
    name: Build and Test
    defaults:
      run:
        working-directory: ${{env.working-dir}}
        
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 8 for build and test
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.x.x'
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --configuration Release --no-restore --settings ${{env.test-settings}} --verbosity normal
