name: Publish Docu
on: [push, pull_request] # replace with array '[push, pull_request]' to trigger the action on each push and pull request

env:
  docu-dir: src/TeleScope.Docu/

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - uses: nikeee/docfx-action@v1.0.0
      name: Build Documentation
      with:
        args: ${{env.docu-dir}}docfx.json

    # Publish generated site using GitHub Pages
    - uses: maxheld83/ghpages@master
      name: Publish Documentation on GitHub Pages
      env:
        BUILD_DIR: ${{env.docu-dir}}_site # docfx's default output directory is _site
        GH_PAT: ${{secrets.GH_PAGES}}
